version: '3.7'

services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "praktikum"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app:
    build: ./
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      APIPort: ":8080"
      DB_ADDRESS: "db-mysql:3306"
      DB_NAME: "praktikum"
    ports:
      - "80:8080"